name: First Workflow
on: push
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: catFile
      run: RESULT=$(cat test.txt) >> "$GITHUB_ENV"
      
    - name: Echo 
      run: echo ${{ env.result }}
