name: First Workflow
on: push
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Read file
      id: read_file
      run: echo "RESULT=$(cat test.txt)" >> "$GITHUB_ENV"

    - name: Echo
      run: echo "Res- ${{ env.RESULT }}"
