name: First Workflow
on: push
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Append files
      id: read_file
      run: |
        
        RESULTFILE=result.yml
        printf 'apiVersion: v1\nkind: ConfigMap\nmetadata:\n\nname: game-demo\ndata:\n' >> "$RESULTFILE"
        cd cfg
        for CONF in *; do
          echo "  $CONF: |" >> "../$RESULTFILE"
          ls
          while IFS= read -r LINE || [ -n "$LINE" ]; do
            echo "    $LINE" >> "../$RESULTFILE"
          done < $CONF
          cat ../$RESULTFILE
        done
        
    - name: Cat
      run: cat result.yml
