name: First Workflow
on: push
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Append files
      id: read_file
      run: |
        
        RESULTFILE=result.yml
        printf 'apiVersion: v1\nkind: ConfigMap\nmetadata:\n\nname: game-demo\ndata:' >> "$RESULTFILE"
        ls
        for CONF in $(ls cfg); do
          echo "  $CONF: |" >> "$RESULTFILE"

          while IFS= read -r LINE || [ -n "$LINE" ]; do
            echo "    $LINE" >> "$RESULTFILE"
          done < $CONF
          cat $RESULTFILE
        done
        
    - name: Cat
      run: cat $RESULTFILE
